let phraseContainer = [`“You've got to get up every morning with determination if you're going to go to bed with satisfaction.” — George Lorimer`, `“Education is the most powerful weapon which you can use to change the world.” — Nelson Mandela`, `“The most difficult thing is the decision to act, the rest is merely tenacity.” —Amelia Earhart`, `“You’ll find that education is just about the only thing lying around loose in this world, and it’s about the only thing a fellow can have as much of as he’s willing to haul away.” —John Graham`, `“Take the attitude of a student, never be too big to ask questions, never know too much to learn something new.” —Augustine Og Mandino`, `“The elevator to success is out of order. You’ll have to use the stairs, one step at a time.” — Joe Girard`, `“Be a positive energy trampoline – absorb what you need and rebound more back.” — Dave Carolan`, `“People often say that motivation doesn’t last. Well, neither does bathing – that’s why we recommend it daily.” — Zig Ziglar`, `“I am so clever that sometimes I don’t understand a single word of what I am saying.” — Oscar Wilde`, `“Life is like a sewer… what you get out of it depends on what you put into it.” — Tom Lehrer`, `“I always wanted to be somebody, but now I realise I should have been more specific.” — Lily Tomlin`, `“Individual commitment to a group effort—that is what makes a team work, a company work, a society work, a civilisation work.” — Vince Lombardi`, `“Teamwork is the ability to work together toward a common vision. The ability to direct individual accomplishments toward organizational objectives. It is the fuel that allows common people to attain uncommon results.” — Andrew Carnegie`, `“Coming together is a beginning. Keeping together is progress. Working together is success.” — Henry Ford`, `“Remember, teamwork begins by building trust. And the only way to do that is to overcome our need for invulnerability.” — Patrick Lencioni`, `“I invite everyone to choose forgiveness rather than division, teamwork over personal ambition.” — Jean-Francois Cope`, `“If you believe something needs to exist, if it's something you want to use yourself, don't let anyone ever stop you from doing it.” —Tobias Lütke`, `“If you really want to do something, you'll find a way. If you don't, you'll find an excuse.” ―Jim Rohn`]


function phraseGenerator(phrasesList){
    let randomNum = Math.ceil(((Math.random())*10))
    console.log(phraseContainer[randomNum]);
}



phraseGenerator(phraseContainer)